import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1 className='text-3xl underline'>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<button className='btn'>daisyUI</button>
			</main>
		</div>
	);
}
